version: 2
exclude_patterns: # Exclude files and/or directories from analysis
  - "src/platforms/dialogflow/index.ts"
  - "src/index.ts"
  - "test/**"
  - "hello-world/**"
plugins:
  nodesecurity:
    enabled: true
  git-legal:
    enabled: true

  shellcheck:
    enabled: true
  fixme:
    enabled: true
