version: 2
exclude_patterns: # Exclude files and/or directories from analysis
  - "src/platforms/dialogflow/index.ts"
  - "src/index.ts"
  - "test/**"
  - "hello-world/**"
  - "**/node_modules/"
plugins:
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  fixme:
    enabled: true
